#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ollama"
name = "Ollama"
description.en = "Get up and running with large language models."

version = "0.9.1~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://ollama.com/"
code = "https://github.com/ollama/ollama"
cpe = "cpe:2.3:a:ollama:ollama"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "2G"
ram.build = "50M"
ram.runtime = "4G"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]

    amd64.url = "https://github.com/ollama/ollama/releases/download/v0.9.1/ollama-linux-amd64.tgz"
    amd64.sha256 = "ef2aba89fc7a94f6b6c5e30227eacbd0fac29504733cd6fb3478a93336c70dbc"
    
    arm64.url = "https://github.com/ollama/ollama/releases/download/v0.9.1/ollama-linux-arm64.tgz"
    arm64.sha256 = "2a50582d171a7de82dba478fc68459730e884b935dd8eed6cf8e1e027c84782e"
    
    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*linux-amd64.tgz"
    autoupdate.asset.arm64 = ".*linux-arm64.tgz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 11434
    main.fixed = true
