#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ollama"
name = "Ollama"
description.en = "Get up and running with large language models."

version = "0.9.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "MIT"
website = "https://ollama.com/"
code = "https://github.com/ollama/ollama"
cpe = "cpe:2.3:a:ollama:ollama"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]

    amd64.url = "https://github.com/ollama/ollama/releases/download/v0.9.0/ollama-linux-amd64.tgz"
    amd64.sha256 = "ae9cebd61552d6cf3c527cb88e3a4865a25f22950aa8bb5328887ffd96cfd22a"
    in_subdir = false
    
    arm64.url = "https://github.com/ollama/ollama/releases/download/v0.9.0/ollama-linux-arm64.tgz"
    arm64.sha256 = "288b6f7ed9175476943c0c01f21df1de21df590b0b3ed5dee16a5285d5da84e4"
    in_subdir = false

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 11434
    main.fixed = true
